/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Go Auth API
 * Gin + JWT 認証API
 * OpenAPI spec version: 1.0
 */
import type { DtoUserSubDTO } from './dtoUserSubDTO';

export interface DtoLoginResponse {
  accessToken?: string;
  refreshToken?: string;
  user?: DtoUserSubDTO;
}
