/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Go Auth API
 * Gin + JWT 認証API
 * OpenAPI spec version: 1.0
 */
import type { DtoTokenDTO } from './dtoTokenDTO';

export interface DtoTokenResponse {
  data?: DtoTokenDTO;
}
