AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: DynamoDB table for storing refresh tokens

Resources:
  RefreshTokenTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: golang_api_sample_refresh_token
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: refresh_token_id
          AttributeType: S
      KeySchema:
        - AttributeName: refresh_token_id
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: expires_at
        Enabled: true

Outputs:
  RefreshTokenTableName:
    Description: テーブル名
    Value: !Ref RefreshTokenTable
