version = 0.1
[Y.deploy.parameters]
stack_name = "golang-api-sample-refresh-token-table"
resolve_s3 = true
s3_prefix = "golang-api-sample-refresh-token-table"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
