# builder stage
FROM golang:1.24.3 AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .

RUN go build -o /main .

# runtime stage
FROM debian:stable-slim

WORKDIR /app
COPY --from=builder /main .

# ポート設定（Goのmainで8080使用している想定）
EXPOSE 8080

CMD ["./main"]
