name: golang-api-docker-sample
services:
  go:
    build: .
    ports:
      - '8080:8080'
    volumes:
      - .:/app

  mysql:
    image: mysql:8.0.30
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - ./docker/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - '3306:3306'

  mysql_test:
    image: mysql:8.0.30
    platform: linux/amd64
    container_name: mysql_test
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go_auth_test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3308:3306'
    command: --default-authentication-plugin=mysql_native_password
