# builder stage
FROM golang:1.24.4-alpine3.22 AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .

RUN go build -o /main .

# runtime stage
FROM alpine:3.22

WORKDIR /app
COPY --from=builder /main .

# ポート設定（Goのmainで8080使用している想定）
EXPOSE 8080

CMD ["./main"]
